language: node_js
node_js:
  - "node"
sudo: required
before_install:
  - cd src
install:
  - npm install
  - npm install swagger-ui-express --save
  - npm install swagger-jsdoc --save
script:
  - npm test
